<a href="https://colab.research.google.com/github/Shamil2007/Python-Tutorials/blob/main/Python-Tutorials/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical Computing in Python
- Let's dive into NumPy, the fundamental package for scientific computing in Python. NumPy provides support for large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays.

In [1]:
import numpy as np

# NumPy Arrays

Why NumPy Arrays?
- Efficiency: Store data more compactly than Python lists

- Speed: Optimized C backend for fast operations

- Functionality: Rich set of built-in operations

- Interoperability: Foundation for pandas, scikit-learn, etc.

In [2]:
# From Python lists
arr1d = np.array([1, 2, 3, 4, 5])         # 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print("1D Array:")
print(arr1d)
print("\n2D Array:")
print(arr2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
# Special arrays
zeros_arr = np.zeros(5)
print(f"1D array filled with zeros (length 5): {zeros_arr}")
print(100 * '_')

ones_arr = np.ones((2, 3))
print(f"2D array filled with ones (2x3):\n{ones_arr}")
print(100 * '_')

identity_matrix = np.eye(3)
print(f"3x3 Identity matrix:\n{identity_matrix}")
print(100 * '_')

range_arr = np.arange(0, 10, 2)
print(f"Range array from 0 to 10 with step 2: {range_arr}")
print(100 * '_')

linspace_arr = np.linspace(0, 1, 5)
print(f"Linearly spaced array from 0 to 1 with 5 values: {linspace_arr}")

1D array filled with zeros (length 5): [0. 0. 0. 0. 0.]
____________________________________________________________________________________________________
2D array filled with ones (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]
____________________________________________________________________________________________________
3x3 Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
____________________________________________________________________________________________________
Range array from 0 to 10 with step 2: [0 2 4 6 8]
____________________________________________________________________________________________________
Linearly spaced array from 0 to 1 with 5 values: [0.   0.25 0.5  0.75 1.  ]


In [4]:
# Reproducible randomness
np.random.seed(42)

# Random arrays
rand_uniform = np.random.rand(3, 2)
print(f"Uniform distribution (0-1): {rand_uniform}")
print(100 * '_')

arr_uniform = np.random.uniform(1, 5, size=(3, 2))
print(f"Using np.random.uniform(): {arr_uniform}")
print(100 * '_')


rand_normal = np.random.rand(20)
print(f"Standard normal distribution {rand_normal}")
print(100 * '_')

rand_int = np.random.randint(1, 10, size=5)
print(f"Random integers {rand_int}")

Uniform distribution (0-1): [[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]
____________________________________________________________________________________________________
Using np.random.uniform(): [[1.23233445 4.46470458]
 [3.40446005 3.83229031]
 [1.08233798 4.87963941]]
____________________________________________________________________________________________________
Standard normal distribution [0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041
 0.60754485 0.17052412]
____________________________________________________________________________________________________
Random integers [7 2 4 9 2]


#Array Attributes

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:")
print(arr)
print()

print("Properties:")
print(f"- Number of dimensions     : {arr.ndim}")
print(f"- Shape (rows, columns)    : {arr.shape}")
print(f"- Total number of elements : {arr.size}")
print(f"- Data type of elements    : {arr.dtype}")

Array:
[[1 2 3]
 [4 5 6]]

Properties:
- Number of dimensions     : 2
- Shape (rows, columns)    : (2, 3)
- Total number of elements : 6
- Data type of elements    : int64


In [6]:
a = np.array([1, 2, 4])
b = np.array([4, 5, 6])

print("Array A:", a)
print("Array B:", b)
print()

# Element-wise operations
print("Element-wise Addition (A + B):", a + b)
print("Multiply A by 2 (A * 2):", a * 2)
print("Square of A (A ** 2):", a ** 2)

Array A: [1 2 4]
Array B: [4 5 6]

Element-wise Addition (A + B): [ 5  7 10]
Multiply A by 2 (A * 2): [2 4 8]
Square of A (A ** 2): [ 1  4 16]


In [7]:
# Dot product of vectors a and b
dot_product = np.dot(a, b)
print("Dot product of a and b:", dot_product) # (1*4 + 2*5 + 3*6)

Dot product of a and b: 38


In [8]:
# Broadcasting example: adding scalar 5 to each element in array a
result = a + 5
print("Result of broadcasting (a + 5):", result)

Result of broadcasting (a + 5): [6 7 9]


#Practice Exercieses 1

- Create a 3x3 array of random numbers between 5 and 10

- Create a 5x5 identity matrix and multiply it by 3

- Generate an array of 20 evenly spaced numbers between -1 and 1

In [9]:
# Method 1: Using np.random.uniform()
arr_uniform = np.random.uniform(5, 10, size=(3, 3))
print("Using np.random.uniform():")
print(arr_uniform)

# Method 2: Using np.random.rand() scaled and shifted
arr_scaled = 5 + (10 - 5) * np.random.rand(3, 3)
print("\nUsing np.random.rand() scaled:")
print(arr_scaled)

Using np.random.uniform():
[[6.92708251 5.07983126 6.15446913]
 [6.20512733 8.41631759 8.04998329]
 [9.16597456 5.86682327 6.95530304]]

Using np.random.rand() scaled:
[[5.91118044 8.77680705 7.12577937]
 [6.03970831 7.83850164 5.15656646]
 [9.21142387 7.24877067 6.97575118]]


In [10]:
# Create identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Multiply by 3
scaled_matrix = 3 * identity_matrix
print("\nMultiplied by 3:")
print(scaled_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Multiplied by 3:
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 3.]]


In [11]:
# Using np.linspace()
evenly_spaced = np.linspace(-1, 1, 20)
print("20 evenly spaced numbers between -1 and 1:")
print(evenly_spaced)

20 evenly spaced numbers between -1 and 1:
[-1.         -0.89473684 -0.78947368 -0.68421053 -0.57894737 -0.47368421
 -0.36842105 -0.26315789 -0.15789474 -0.05263158  0.05263158  0.15789474
  0.26315789  0.36842105  0.47368421  0.57894737  0.68421053  0.78947368
  0.89473684  1.        ]


#Basic Indexing

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Single element
arr[0, 1] # (row 0, column 1)

np.int64(2)

In [13]:
arr[:2, 1:] # Rows 0-1, columns 1-end

array([[2, 3],
       [5, 6]])

In [14]:
arr[::2, ::2] # Every other row and column

array([[1, 3],
       [7, 9]])

#Boolean Indexing

In [15]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# Filter elements
arr[arr > 3]

array([4, 5, 9, 6])

In [16]:
# Multiple conditions
arr[(arr > 2) & (arr < 6)]

array([3, 4, 5])

In [17]:
# Set values conditionally
arr[arr < 3] = 0
arr

array([3, 0, 4, 0, 5, 9, 0, 6])

#Fancy Indexing

In [18]:
arr = np.arange(10, 100, 10)
print(f"Array : {arr}")

# Integer array indexing
arr[[1, 3, 5]]

Array : [10 20 30 40 50 60 70 80 90]


array([20, 40, 60])

In [19]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[[0, 2]] # Rows 0 and 2

array([[1, 2, 3],
       [7, 8, 9]])

In [20]:
arr2d[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

#Practice Exercises 2

- Extract the diagonal of a 4x4 matrix

- Create a checkerboard pattern using slicing

- Replace all odd numbers in an array with -1

In [21]:
arr = np.random.uniform(1, 10, size=(4, 4))

diagonal = []

for i in range(4):
    diagonal.append(arr[i][i])

print("Original 4x4 matrix:")
print(arr)
print("\nMatrix with only diagonal elements:")
print(diagonal)

Original 4x4 matrix:
[[9.33992979 7.54544796 3.93886692 6.13399577]
 [5.68750834 9.65054822 8.60080464 7.72588099]
 [5.85722919 6.28076049 9.68729777 6.46330823]
 [3.48399264 3.66646155 2.48740245 1.14072766]]

Matrix with only diagonal elements:
[np.float64(9.339929792144147), np.float64(9.650548219144142), np.float64(9.687297765377242), np.float64(1.1407276606707453)]


In [22]:
# With diagonal functions
np.diag(arr)

array([9.33992979, 9.65054822, 9.68729777, 1.14072766])

In [23]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("Checkerboard pattern:")
print(checkerboard)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
arr = np.arange(25)
arr[arr % 2 == 1] = -1

print("Modified array (odd numbers replaced with -1):")
print(arr)

Modified array (odd numbers replaced with -1):
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1 20 -1 22 -1
 24]


#Reshaping Arrays

In [25]:
arr = np.arange(12)
print(f"Arr: {arr}")

# Reshape to 3x4
arr = arr.reshape(3, 4)
print(f"Reshaped array:")
print(arr)
print(f"Dim: {arr.shape}")

Arr: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Dim: (3, 4)


In [26]:
# Flatten
arr_flatten = arr.reshape(-1) # or arr.flatten()
print(arr_flatten)
print(f"Dim: {arr_flatten.shape}")

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Dim: (12,)


In [27]:
column_vector = arr[:, np.newaxis] # Convert to column vector
print(column_vector)
print(f"Dim: {column_vector.shape}")

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
Dim: (3, 1, 4)


#Stacking Arrays

In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# Horizontal stack
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [30]:
np.column_stack((a, b))

array([[1, 4],
       [2, 5],
       [3, 6]])

#Splitting Arrays

In [31]:
arr = np.arange(12).reshape(3, 4)
print(f"Arr:")
print(arr)

# Split vertically
np.vsplit(arr, 3) # 3 sub-arrays

Arr:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [32]:
# Split horizontally
np.hsplit(arr, 2)  # 2 sub-arrays

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [33]:
# Uneven splitting
np.array_split(arr, 2, axis=0)  # Split rows into 2 parts

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]

#Practice Exercises 3

- Convert a 1D array of 24 elements into a 3D array (2x3x4)

- Stack two arrays vertically and horizontally

- Split an array into 4 equal parts

In [34]:
arr1D = np.arange(24)
print(f"1D array:\n{arr1D}")

arr1D.resize(2, 3, 4)  # modifies arr1D itself
print("\nReshaped to 3D array:")
print(arr1D)

1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped to 3D array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [35]:
a = np.random.rand(5)
b = np.random.rand(5)

print(f"Vertically: ")
print(np.vstack((a, b)))
print(80 * '-')

print(f"Horizontally: ")
print(np.hstack((a, b)))

Vertically: 
[[0.42340148 0.39488152 0.29348817 0.01407982 0.1988424 ]
 [0.71134195 0.79017554 0.60595997 0.92630088 0.65107703]]
--------------------------------------------------------------------------------
Horizontally: 
[0.42340148 0.39488152 0.29348817 0.01407982 0.1988424  0.71134195
 0.79017554 0.60595997 0.92630088 0.65107703]


In [36]:
arr = np.arange(20)  # Total 20 elements
print("Original array:")
print(arr)

# Split into 4 equal parts
parts = np.split(arr, 4)

print("\nArray split into 4 parts:")
for i, part in enumerate(parts, 1):
    print(f"Part {i}: {part}")

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Array split into 4 parts:
Part 1: [0 1 2 3 4]
Part 2: [5 6 7 8 9]
Part 3: [10 11 12 13 14]
Part 4: [15 16 17 18 19]


#Math operations

In [37]:
arr = np.array([1, 4, 9, 16, 25])

# Math operations
np.sqrt(arr)  # Square root

array([1., 2., 3., 4., 5.])

In [38]:
np.exp(arr)   # Exponential

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [39]:
np.log(arr)   # Natural log

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])

In [40]:
np.sin(arr)   # Trigonometric functions

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

#Linear Algebra Functions for Machine Learning

Matrix Transpose

In [41]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A: ")
print(A)
print("A transpose: ")
A.T

A: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
A transpose: 


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Matrix Multiplication

In [42]:
A = np.array([[1, 2], [3, 4]])  # 2x2
B = np.array([[5, 6], [7, 8]])  # 2x2

C = A @ B           # Matrix Multiplication Operator
C

array([[19, 22],
       [43, 50]])

In [43]:
np.dot(A, B)        # Dot Product / Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [44]:
np.matmul(A, B)     # Strict Matrix Multiplication

array([[19, 22],
       [43, 50]])

Solving Linear Systems

In [45]:
# System: 3x + y = 9; x + 2y = 8
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

x = np.linalg.solve(A, b)  # Solution: x=2, y=3

Eigen Decomposition

In [46]:
cov_matrix = np.array([[2, -1], [-1, 2]])  # Covariance matrix

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvalues, eigenvectors

(array([3., 1.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

Matrix Norms

In [47]:
v = np.array([3, 4])

l2_norm = np.linalg.norm(v)       # L2 norm (Euclidean)
l1_norm = np.linalg.norm(v, ord=1) # L1 norm (Manhattan)
l2_norm, l1_norm

(np.float64(5.0), np.float64(7.0))

Matrix Inverse

In [48]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.7],
       [-0.2,  0.4]])

Trace and Determinant

In [50]:
M = np.array([[1, 2], [3, 4]])

tr = np.trace(M)    # Sum of diagonal
print(f"Sum of dioganal: {tr}")

det = np.linalg.det(M)  # Determinant
print(f"Determinant: {det}")

Sum of dioganal: 5
Determinant: -2.0000000000000004
